---

- hosts: 10.10.10.141
  become: true
  tasks:

  - name: UPDATE DNF cache
    ansible.builtin.dnf:
     update_cache: yes
        
  - name: REMOVE tmux, tftp cli package 
    ansible.builtin.dnf:
      name: 
        - tmux
        - tftp
        - syslinux-tftpboot.noarch
      state: removed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"

  - name: INSTALL tmux, tftp cli, tftpd package
    dnf:
      name: 
        - tmux
        - tftp
        - tftp-server
        - syslinux-tftpboot.noarch
      state: installed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"
  
  - name: CHECK for installed tmux, tftp cli, tftpd package
    dnf:
      name: 
        - tmux
        - tftp
        - tftp-server
        - syslinux-tftpboot.noarch
      state: installed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"
