---

- hosts: general_centos_8_stream_grp2 
  become: true
  tasks:

  - name: UPDATE DNF cache
    ansible.builtin.dnf:
     update_cache: yes
        
  - name: REMOVE tmux, tftp cli package 
    ansible.builtin.dnf:
      name: 
        - tmux
        - tftp
        - syslinux-tftpboot.noarch
      state: removed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"

  - name: INSTALL tmux, tftp cli, tftpd package
    dnf:
      name: 
        - tmux
        - tftp
        - tftp-server
        - syslinux-tftpboot.noarch
      state: installed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"
  
  - name: CHECK for installed tmux, tftp cli, tftpd package
    dnf:
      name: 
        - tmux
        - tftp
        - tftp-server
        - syslinux-tftpboot.noarch
      state: installed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"

  - name: start tftpd
    service:
      name: tftp
      state: started
      enabled: true
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"


  - name: COPY file to /tmp
    tags: CopyFiles
    copy:
      src: default_site.html
      dest: /tmp/_copied_site.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"

  - name: change LINE in file /tmp/_copied_site.html
    lineinfile:
      path: /tmp/_copied_site.html
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@my.net
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"
    register: status_copiedsitehtml


  - name: restart tftp service when _copied_site.html was changed
    service:
      name: tftp
      state: restarted
    when: status_copiedsitehtml.changed
