---

- hosts: 10.10.10.141
  become: true
  tasks:

  - name: UPDATE DNF cache
    ansible.builtin.dnf:
     update_cache: yes
        
  - name: REMOVE tmux package 
    ansible.builtin.dnf:
      name: tmux
      state: removed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"

  - name: INSTALL tmux package
    dnf:
      name: tmux
      state: installed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"
  
  - name: CHECK for installed tmux package
    dnf:
      name: tmux
      state: installed
    when: ansible_distribution_release == "Stream" and ansible_distribution_file_variety == "CentOS" and ansible_distribution_major_version == "8"
